
  name: Github Actions demo
  on: [push]
  jobs:
    Test:
      runs-on: ubuntu-latest
      steps:
        - uses: action/checkout@v2
        - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
        - run: python main.py
